# --- FONT ---
font_family      JetBrainsMono Nerd Font
font_size        11.0

# --- LOOK & FEEL ---
# Fenster-Dekorationen (Titelleiste etc.) komplett weg
hide_window_decorations yes

# Hintergrund-Transparenz (0.0 ist komplett durchsichtig, 1.0 solide)
background_opacity 0.7

# Padding (Abstand vom Rand, damit der Text nicht klebt)
window_padding_width 15

# Cursor (Blinken aus für mehr Zen)
cursor_blink_interval 0

# --- COLORS ---
# Ein sehr dunkles Grau/Schwarz für den Minimal-Vibe
background #111111
foreground #eeeeee
