#!/usr/bin/env python3
import json
import os
from pathlib import Path

THEME_DIR = Path(__file__).parent
PALETTE_FILE = THEME_DIR / "palette.json"
GEN_DIR = THEME_DIR / "generated"

def main():
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    with open(PALETTE_FILE, "r") as f:
        data = json.load(f)
    
    colors = data.get("colors", {})

    # 1. Generate GTK CSS (Waybar)
    css_lines = ["/* Auto-generated by theme/apply.py - DO NOT EDIT MANUALLY */"]
    for k, v in colors.items():
        if not k.startswith("hypr_"):
            css_name = k.replace("_", "-")
            css_lines.append(f"@define-color {css_name} {v};")
    (GEN_DIR / "colors.css").write_text("\n".join(css_lines) + "\n")

    # 2. Generate Rofi RASI
    rasi_lines = [
        "/* Auto-generated by theme/apply.py - DO NOT EDIT MANUALLY */",
        "* {"
    ]
    for k, v in colors.items():
        if not k.startswith("hypr_"):
            rasi_name = k.replace("_", "-")
            rasi_lines.append(f"    {rasi_name}: {v};")
    rasi_lines.append("}")
    (GEN_DIR / "colors.rasi").write_text("\n".join(rasi_lines) + "\n")

    # 3. Generate Hyprland Lua
    lua_lines = [
        "-- Auto-generated by theme/apply.py - DO NOT EDIT MANUALLY",
        "return {"
    ]
    for k, v in colors.items():
        lua_lines.append(f'    {k} = "{v}",')
    lua_lines.append("}")
    (GEN_DIR / "colors.lua").write_text("\n".join(lua_lines) + "\n")

    # 4. Generate Kitty Conf
    kitty_lines = [
        "# Auto-generated by theme/apply.py - DO NOT EDIT MANUALLY",
        f"background {colors.get('term_bg', '#111111')}",
        f"foreground {colors.get('term_fg', '#eeeeee')}",
        f"selection_background {colors.get('accent', '#D97736')}",
        f"selection_foreground {colors.get('term_bg', '#111111')}",
        "",
        "# 16-color ANSI Palette"
    ]
    for i in range(16):
        key = f"color{i}"
        if key in colors:
            kitty_lines.append(f"{key} {colors[key]}")
    (GEN_DIR / "colors.conf").write_text("\n".join(kitty_lines) + "\n")

    # 5. Generate JSON
    (GEN_DIR / "colors.json").write_text(json.dumps(data, indent=2) + "\n")

    print("Theme applied successfully across all targets!")

if __name__ == "__main__":
    main()
