#!/usr/bin/env python3
import json
import sys
import os
import re

def to_hex_raw(val):
    if not val:
        return "FFFFFF"
    val = str(val).strip().lstrip("#")
    if val.startswith("0x") or val.startswith("0X"):
        val = val[2:]
        if len(val) == 8:
            val = val[2:]  # strip alpha
    if len(val) == 6:
        return val.upper()
    return "FFFFFF"

def to_hypr_color(val, alpha=None):
    if not val:
        return "rgb(255, 255, 255)"
    val = str(val).strip()
    if val.startswith("#"):
        h = val.lstrip("#")
        if len(h) == 6:
            r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
            if alpha is not None and alpha < 1.0:
                return f"rgba({r}, {g}, {b}, {alpha:.2f})"
            return f"rgb({r}, {g}, {b})"
        elif len(h) == 8:
            r, g, b, a = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16), int(h[6:8], 16) / 255.0
            if alpha is not None:
                a = alpha
            return f"rgba({r}, {g}, {b}, {a:.2f})"
    elif val.startswith("0x") or val.startswith("0X"):
        h = val[2:]
        if len(h) == 8:
            a, r, g, b = int(h[0:2], 16) / 255.0, int(h[2:4], 16), int(h[4:6], 16), int(h[6:8], 16)
            if alpha is not None:
                a = alpha
            if a < 1.0:
                return f"rgba({r}, {g}, {b}, {a:.2f})"
            return f"rgb({r}, {g}, {b})"
    elif val.startswith("rgba"):
        if alpha is not None:
            parts = re.findall(r"[\d\.]+", val)
            if len(parts) >= 3:
                return f"rgba({parts[0]}, {parts[1]}, {parts[2]}, {alpha:.2f})"
        return val
    elif val.startswith("rgb"):
        return val
    return f"rgb({val})"

def generate_theme_files(preset_path):
    if not os.path.exists(preset_path):
        print(f"Error: Preset file {preset_path} not found.")
        sys.exit(1)

    with open(preset_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    colors = data.get("colors", {})
    name = data.get("name", "Custom Theme")

    generated_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "generated")
    os.makedirs(generated_dir, exist_ok=True)

    # 1. Save colors.json
    colors_json_path = os.path.join(generated_dir, "colors.json")
    with open(colors_json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2)

    # 2. Save colors.conf (Kitty / Hyprland config format)
    colors_conf_path = os.path.join(generated_dir, "colors.conf")
    conf_lines = [
        "# Auto-generated by theme/apply.py - DO NOT EDIT MANUALLY",
        f"background {colors.get('term_bg', colors.get('color0', '#1E1E2E'))}",
        f"foreground {colors.get('term_fg', colors.get('color15', '#CDD6F4'))}",
        f"selection_background {colors.get('accent', '#CBA6F7')}",
        f"selection_foreground {colors.get('term_bg', colors.get('color0', '#1E1E2E'))}",
        "",
        "# 16-color ANSI Palette"
    ]
    for i in range(16):
        key = f"color{i}"
        if key in colors:
            conf_lines.append(f"{key} {colors[key]}")
    with open(colors_conf_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(conf_lines) + "\n")

    # 3. Save colors.css (Waybar / GTK CSS format)
    colors_css_path = os.path.join(generated_dir, "colors.css")
    css_lines = ["/* Auto-generated by theme/apply.py - DO NOT EDIT MANUALLY */"]
    css_mapping = [
        ("bg-base", colors.get("bg_base")),
        ("bg-input", colors.get("bg_input")),
        ("bg-box", colors.get("bg_box")),
        ("bg-box-solid", colors.get("bg_box_solid")),
        ("fg-primary", colors.get("fg_primary")),
        ("fg-muted", colors.get("fg_muted")),
        ("fg-dark", colors.get("fg_dark")),
        ("accent", colors.get("accent")),
        ("accent-hover", colors.get("accent_hover")),
        ("accent-bg", colors.get("accent_bg")),
        ("border", colors.get("border")),
        ("border-subtle", colors.get("border_subtle")),
        ("inner-border", colors.get("inner_border")),
        ("waybar-border", colors.get("waybar_border", "transparent")),
        ("cc-border", colors.get("cc_border", "transparent")),
        ("warning", colors.get("warning")),
        ("danger", colors.get("danger")),
        ("term-bg", colors.get("term_bg")),
        ("term-fg", colors.get("term_fg")),
    ]
    for key, val in css_mapping:
        if val:
            css_lines.append(f"@define-color {key} {val};")
    for i in range(16):
        key = f"color{i}"
        if key in colors:
            css_lines.append(f"@define-color {key} {colors[key]};")
    with open(colors_css_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(css_lines) + "\n")

    # 4. Save colors.rasi (Rofi theme format)
    colors_rasi_path = os.path.join(generated_dir, "colors.rasi")
    rasi_lines = [
        "/* Auto-generated by theme/apply.py - DO NOT EDIT MANUALLY */",
        "* {"
    ]
    for key, val in css_mapping:
        if val:
            rasi_lines.append(f"    {key}: {val};")
    for i in range(16):
        key = f"color{i}"
        if key in colors:
            rasi_lines.append(f"    {key}: {colors[key]};")
    rasi_lines.append("}")
    with open(colors_rasi_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(rasi_lines) + "\n")

    # 5. Save colors.lua (Neovim / Lua format)
    colors_lua_path = os.path.join(generated_dir, "colors.lua")
    lua_lines = [
        "-- Auto-generated by theme/apply.py - DO NOT EDIT MANUALLY",
        "return {"
    ]
    lua_items = []
    for key in ["bg_base", "bg_input", "bg_box", "bg_box_solid", "fg_primary", "fg_muted", "fg_dark", 
                "accent", "accent_hover", "accent_bg", "border", "border_subtle", "inner_border", 
                "waybar_border", "cc_border", "warning", "danger", "hypr_active_border", 
                "hypr_inactive_border", "term_bg", "term_fg"]:
        if key in colors:
            lua_items.append(f'    {key} = "{colors[key]}"')
    for i in range(16):
        key = f"color{i}"
        if key in colors:
            lua_items.append(f'    {key} = "{colors[key]}"')
    lua_lines.append(",\n".join(lua_items))
    lua_lines.append("}")
    with open(colors_lua_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lua_lines) + "\n")

    # 6. Save colors-hyprlock.conf (Hyprlock format)
    colors_hyprlock_path = os.path.join(generated_dir, "colors-hyprlock.conf")
    hyprlock_lines = [
        "# Auto-generated by theme/apply.py - DO NOT EDIT MANUALLY",
        f"$bg_base = {to_hypr_color(colors.get('bg_base', '#54382B'))}",
        f"$bg_base_alpha = {to_hypr_color(colors.get('bg_base', '#54382B'), alpha=0.95)}",
        f"$bg_input = {to_hypr_color(colors.get('bg_input', '#664839'))}",
        f"$border = {to_hypr_color(colors.get('border', '#7A523D'))}",
        f"$border_subtle = {to_hypr_color(colors.get('border_subtle', colors.get('border', '#7A523D')), alpha=0.5)}",
        f"$fg_primary = {to_hypr_color(colors.get('fg_primary', '#F2E3D5'))}",
        f"$fg_muted = {to_hypr_color(colors.get('fg_muted', '#C2AA95'))}",
        f"$accent = {to_hypr_color(colors.get('accent', '#FF8C00'))}",
        f"$accent_hover = {to_hypr_color(colors.get('accent_hover', '#FFA022'))}",
        f"$danger = {to_hypr_color(colors.get('danger', '#E74C3C'))}",
        f"$warning = {to_hypr_color(colors.get('warning', '#FF9800'))}",
        "",
        "# Raw hex codes for Pango markup in hyprlock",
        f"$fg_muted_hex = {to_hex_raw(colors.get('fg_muted', 'C2AA95'))}",
        f"$accent_hex = {to_hex_raw(colors.get('accent', 'FF8C00'))}",
        f"$danger_hex = {to_hex_raw(colors.get('danger', 'E74C3C'))}",
        f"$warning_hex = {to_hex_raw(colors.get('warning', 'FF9800'))}",
    ]
    with open(colors_hyprlock_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(hyprlock_lines) + "\n")

    print(f"Successfully applied theme '{name}' from {preset_path}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 apply.py <path_to_preset.json>")
        sys.exit(1)
    generate_theme_files(sys.argv[1])
