[package]
name = "rustbar"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rustbar"
path = "src/main.rs"

[dependencies]
shell-common.workspace = true
smithay-client-toolkit.workspace = true
wayland-client.workspace = true
tiny-skia.workspace = true
rusttype.workspace = true
calloop.workspace = true
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
